/*
CNPJ	Razão Social	Filial	Descricao Estab	Esp	Título	Parc	Data Emissao	Data Pgtº	
Vl.Bruto	Vl.Pago	ISS	INSS	IR	PIS/CONFINS/CSSL	Conta Contábil	CR	Borderô	Banco	Agência	C.Corrente										
                                                                                                                                                                                             
+ 
SELECT * FROM SYS_COMPANY
*/

SELECT 
CASE 
	WHEN LEN(A2_CGC) = 14 THEN 
		SUBSTRING(A2_CGC,1,2) + '.'
		+ SUBSTRING(A2_CGC,3,3) + '.'
		+ SUBSTRING(A2_CGC,6,3) + '/'
		+ SUBSTRING(A2_CGC,9,4) + '-'
		+ SUBSTRING(A2_CGC,13,2) 
	WHEN LEN(A2_CGC) = 11 THEN
		SUBSTRING(A2_CGC,1,3) + '.'
	+ SUBSTRING(A2_CGC,4,3) + '.'
	+ SUBSTRING(A2_CGC,7,3) + '-'
	+ SUBSTRING(A2_CGC,10,2)
	ELSE  A2_CGC
	END
as CNPJ,
  E2_FORNECE AS FORNECEDOR,
  A2_NOME AS [RAZAO SOCIAL], 
  E2_FILIAL AS FILIAL, 
  M0_NOMECOM AS ESTABELECIMENTO, 
  E2_PREFIXO AS PREFIXO,
  E2_TIPO AS TIPO, 
  E2_NUM AS NUMERO, 
  E2_PARCELA AS PARCELA,
  E2_NATUREZ AS NATUREZA,
  ED_DESCRIC AS NATDESC,
  CONVERT(VARCHAR, CONVERT(DATETIME, E2_EMISSAO, 102), 103) AS [DATA EMISSAO], 
  CONVERT(VARCHAR, CONVERT(DATETIME, E2_BAIXA, 102), 103) AS [DATA_PGTO], 
  E2_VALOR + E2_ISS + E2_IRRF + E2_INSS AS VALOR_BRUTO, 
  E2_VALLIQ AS [VL_PAGO], 
  E2_SALDO AS SALDO,
  E2_ISS AS ISS, 
  E2_INSS AS INSS, 
  E2_IRRF AS IRRF, 
  E2_PIS AS PIS,
  E2_COFINS AS COFINS,
  E2_CSLL AS CSLL, 
  E2_HIST AS HISTORICO,
  E2_CONTAD AS [CTA_CONTABIL],
  ISNULL(EA_NUMBOR, E2_NUMBOR) AS BORDERO, 
  CONVERT(VARCHAR, CONVERT(DATETIME,  ISNULL(EA_DATABOR, E2_DTBORDE) , 102), 103)AS [DATA_BORDERO], 
  E2_ZBANCO AS BANCO, 
  E2_ZAGENCI AS AGENCIA, 
  E2_ZCONTA AS [CONTA_CORRENTE] 
FROM 
  SE2010 (NOLOCK) E2 
  INNER JOIN SA2010 A2 (NOLOCK) on (
    A2.D_E_L_E_T_ = '' 
    AND E2_FORNECE = A2_COD 
    AND E2_LOJA = A2_LOJA
  ) 
  INNER JOIN SED010 ED (NOLOCK) on (
	ED.D_E_L_E_T_ = ''
	AND ED_CODIGO = E2_NATUREZ)
  INNER JOIN SYS_COMPANY S (NOLOCK) ON (
    S.D_E_L_E_T_ = '' 
    AND M0_CODFIL = E2_FILIAL
  ) 
  INNER JOIN SEA010 SEA (NOLOCK) ON (
    SEA.D_E_L_E_T_ = '' 
    AND EA_FILORIG = E2_FILIAL 
    AND EA_PREFIXO = E2_PREFIXO 
    AND EA_NUM = E2_NUM 
    AND EA_PARCELA = E2_PARCELA 
    AND EA_TIPO = E2_TIPO 
    AND EA_FORNECE = E2_FORNECE 
    AND EA_LOJA = E2_LOJA
  ) 
where 
  E2_EMISSAO >= '20180101'
  AND E2_TIPO <> 'NT'
  AND E2.D_E_L_E_T_ = ''
  AND A2_CGC = '09075640000135'
order by A2_CGC, E2_FILIAL,  E2_EMISSAO,E2_NUM,E2_PARCELA

/*


SELECT TOP (1)* FROM SED010


Cta.Contabil

Cod. Orcam


*/